project:
  type: website

website:
  title: "Anna-Lena Krause"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - posts.qmd
    tools:
    - icon: twitter
      href: https://twitter.com/AnnaLKrause
    - icon: github
      href: https://github.com/AnnaLenaKrause
    - icon: linkedin
      href: https://www.linkedin.com/in/annalenakrause/

  page-footer: "Made with ❤️, Copywrite 2024, Anna-Lena Krause"
  twitter-card: true


format:
  html:
    theme:
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true



