---
title: "About"
title-block-banner: assets/sea_straight.jpg
background-size: cover;
background-position: center;
---
<style>

#title-block-header {
  margin-block-end: -25rem;
  position: relative;
  margin-top: 1px;
  height: 775px;
}

.quarto-title-banner {
  margin-block-end: 1rem;
  position: relative;
  margin-top: -30px;
  height: 85%;
}

</style>

Hi, I'm Anna, a master's student in Cognitive Neuroscience at Maastricht University. In the past, I have completed bachelor's in Data Science & AI and Psychology. My interests lie in the fields of mental health, neuroscience and women's brain health.

During my academic journey, I have developed a passion for applying machine learning techniques to the mental health and neuroscience domains. Currently I am following this interest during an internship at the University of California, Santa Barbara (UCSB), where I investigate the impact of the sex hormones estradiol and progesterone on brain connectivity during the menstrual cycle. Bonus: The amazing view from the lab, which you can see on the top of this page!

In my free time, I enjoy bouldering, hiking, water colouring, lino cuts.